[custom]
;规则集定义
ruleset=🎯 全球直连,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/ProxyLite.list
#ruleset=🎯 全球直连,[]GEOSITE,CN
#ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
#ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;策略组定义
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚀 节点选择`select`[]节点库`[]初选`[]精选`[]优质节点`[]智能负载`[]核心业务

; 节点组
custom_proxy_group=节点库`select`.*
custom_proxy_group=初选`url-test`.*`https://cp.cloudflare.com/generate_204`1500,,50
custom_proxy_group=精选`url-test`.*`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=优质节点`url-test`(?=.*(fh|香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(深圳|家宽)).)*$`http://www.gstatic.com/generate_204`60,,50

; 业务组
custom_proxy_group=智能负载`load-balance`[]节点库`[]初选`[]精选`[]优质节点`http://www.gstatic.com/generate_204`120,,50
custom_proxy_group=核心业务`fallback`[]节点库`[]初选`[]精选`[]优质节点`http://www.gstatic.com/generate_204`60,,50

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
