[custom]
; 规则集定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/ProxyLite.list
ruleset=🐟 漏网之鱼,[]FINAL

; 策略组定义
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚀 节点选择`select`[]智能负载`[]核心业务`[]香港优质节点`[]备用优质节点`[]初选`[]节点库

; 节点筛选体系
custom_proxy_group=节点库`select`.*
custom_proxy_group=初选`url-test`.*`https://cp.cloudflare.com/generate_204`900,,100
custom_proxy_group=香港优质节点`url-test`^(?=.*(香港|hk|hong)).*$`http://www.gstatic.com/generate_204`127,,100
custom_proxy_group=备用优质节点`url-test`^(?!.*(香港|HK|HongKong)).*$`http://www.gstatic.com/generate_204`307,,100

; 业务应用组
custom_proxy_group=智能负载`load-balance`[]香港优质节点`[]备用优质节点`[]节点库`http://www.gstatic.com/generate_204`120,,30
custom_proxy_group=核心业务`fallback`[]香港优质节点`[]备用优质节点`[]节点库`http://api.zoom.us`60,,20

; 启用配置
enable_rule_generator=true
overwrite_original_rules=true
