[custom]
; 规则集定义
ruleset=🎯 全球直连,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/ProxyLite.list
ruleset=🐟 漏网之鱼,[]FINAL

; 策略组定义
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚀 节点选择`select`[]智能负载`[]核心业务`[]优质节点池

; 节点筛选体系
custom_proxy_group=节点库`select`.*
custom_proxy_group=初筛池`url-test`.*`https://cp.cloudflare.com/generate_204`900,300
custom_proxy_group=精筛池`url-test`[]初筛池`https://www.gstatic.com/generate_204`300,100
custom_proxy_group=香港优质节点`url-test`[]精筛池`(?i)(香港|hk|hong.*?)(?<!深圳)(?<!家宽)`http://www.gstatic.com/generate_204`120,50
custom_proxy_group=备用优质节点`url-test`[]精筛池`(?i)(日本|新加坡|韩国)`http://www.gstatic.com/generate_204`300,80

; 节点池聚合
custom_proxy_group=优质节点池`select`[]香港优质节点`[]备用优质节点

; 业务应用组
custom_proxy_group=智能负载`load-balance`[]优质节点池`http://www.gstatic.com/generate_204`120,30
custom_proxy_group=核心业务`fallback`[]优质节点池`http://api.zoom.us`60,20

; 启用配置
enable_rule_generator=true
overwrite_original_rules=true
