[custom]
ruleset=🎯 全球直连,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/ProxyLite.list
ruleset=🐟 漏网之鱼,[]FINAL

; 策略组
custom_proxy_group=🚀 节点选择`select`[]智能负载`[]核心业务
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择

; 检测组（每个输出1节点）
custom_proxy_group=检测组A`url-test`.*`https://cp.cloudflare.com`600,,50
custom_proxy_group=检测组B`url-test`.*`https://www.gstatic.com`300,,50
custom_proxy_group=检测组C`url-test`.*`https://api.zoom.us`120,,30

; 业务组（多节点输入）
custom_proxy_group=智能负载`load-balance`[]检测组A`[]检测组B`[]检测组C`http://www.gstatic.com`120,,30
custom_proxy_group=核心业务`fallback`[]检测组A`[]检测组B`[]检测组C`https://api.zoom.us`60,,20

enable_rule_generator=true
overwrite_original_rules=true
