[custom]
;规则集定义
ruleset=🎯 全球直连,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://proxy.v2gh.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
#ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;策略组定义
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🌐 其他节点`[]🔄 选择故转`.*
custom_proxy_group=🇭🇰 香港节点`url-test`(?=.*(fh|香港))^((?!(深圳|家宽)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(?=.*(fh|美国))^((?!(深圳|家宽)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌐 其他节点`url-test`^((?!(香港|美国)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`(?=.*(fh|fu))^((?!(深圳|家宽)).)*$`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔄 选择故转`fallback`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🌐 其他节点`[]♻️ 自动选择`http://www.gstatic.com/generate_204`120,,50
;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
