[custom]
;规则集定义
ruleset=🎯 全球直连,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://proxy.v2gh.com/https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/ProxyLite.list
ruleset=🚀 节点选择,https://proxy.v2gh.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
#ruleset=🛑 广告拦截,https://proxy.v2gh.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🎯 全球直连,[]GEOSITE,CN
#ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🐟 漏网之鱼,[]FINAL
;策略组定义
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
#custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]⭐ 测试1`[]⭐ 测试2`[]⭐ 测试3`[]🍃 负载均衡`[]♻️ 自动选择`[]🔄 选择故转`[]🌐 其他节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点
custom_proxy_group=⭐ 测试1`load-balance`[]🍃 负载均衡`[]♻️ 自动选择`[]🔄 选择故转`http://cp.cloudflare.com/204`150,,20
custom_proxy_group=⭐ 测试2`fallback`[]🍃 负载均衡`[]♻️ 自动选择`[]🔄 选择故转`http://cp.cloudflare.com/204`150,,20
custom_proxy_group=⭐ 测试3`url-test`[]🍃 负载均衡`[]♻️ 自动选择`[]🔄 选择故转`http://cp.cloudflare.com/204`150,,20
custom_proxy_group=🔄 选择故转`fallback`[]🌐 其他节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`http://cp.cloudflare.com/204`300,,20
custom_proxy_group=🍃 负载均衡`load-balance`[]🌐 其他节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`http://cp.cloudflare.com/204`300,,20
custom_proxy_group=♻️ 自动选择`url-test`[]🌐 其他节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`http://cp.cloudflare.com/204`300,,20
custom_proxy_group=🇭🇰 香港节点`load-balance`(?=.*(fh|香港|HK|speednode))^((?!(深圳|家宽)).)*$`http://cp.cloudflare.com/204`600,,20
custom_proxy_group=🇯🇵 日本节点`load-balance`(?=.*(日本|JP|Japan|YouTube顺丰资源|Telegram))^((?!(深圳|家宽|香港)).)*$`http://cp.cloudflare.com/204`600,,20
custom_proxy_group=🇸🇬 加坡节点`load-balance`(?=.*(新加坡|SG|b2n.ir))^((?!(深圳|家宽|speednode)).)*$`http://cp.cloudflare.com/204`600,,20
custom_proxy_group=🇺🇲 美国节点`load-balance`(?=.*(fh|美国|US))^((?!(深圳|家宽)).)*$`http://cp.cloudflare.com/204`600,,20
custom_proxy_group=🌐 其他节点`load-balance`^((?!(fh|香港|美国|HK|US|日本|JP|Japan|新加坡|SG|b2n.ir|speednode|YouTube顺丰资源|Telegram)).)*$`http://cp.cloudflare.com/204`600,,20

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
