[custom]
;规则集定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/Direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/youzhi1233/rule/refs/heads/main/ProxyLite.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🎯 全球直连,[]GEOSITE,CN
#ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🐟 漏网之鱼,[]FINAL
;策略组定义
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
#custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]⭐ 测试1`[]⭐ 测试2`[]⭐ 测试3`[]🍃 负载均衡`[]♻️ 自动选择`[]🔄 选择故转`[]🌐 其他节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点
custom_proxy_group=⭐ 测试1`load-balance`[]🍃 负载均衡`[]♻️ 自动选择`[]🔄 选择故转`http://cp.cloudflare.com/204`30,,20
custom_proxy_group=⭐ 测试2`url-test`[]🍃 负载均衡`[]♻️ 自动选择`[]🔄 选择故转`http://cp.cloudflare.com/204`30,,20
custom_proxy_group=⭐ 测试3`fallback`[]🔄 选择故转`[]♻️ 自动选择`[]🍃 负载均衡`http://cp.cloudflare.com/204`30,,20
custom_proxy_group=🔄 选择故转`fallback`[]🌐 其他节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`http://cp.cloudflare.com/204`30,,20
custom_proxy_group=🍃 负载均衡`load-balance`[]🌐 其他节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`http://cp.cloudflare.com/204`30,,20
custom_proxy_group=♻️ 自动选择`url-test`[]🌐 其他节点`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 加坡节点`http://cp.cloudflare.com/204`30,,20
custom_proxy_group=🇭🇰 香港节点`load-balance`(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(深港|US|家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$`http://cp.cloudflare.com/204`300,,20
custom_proxy_group=🇯🇵 日本节点`load-balance`(?=.*(日本|未知|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(深港|家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://cp.cloudflare.com/204`300,,20
custom_proxy_group=🇸🇬 加坡节点`load-balance`(?=.*(新加坡|德国|狮城|SG|Singapore))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$`http://cp.cloudflare.com/204`300,,20
custom_proxy_group=🇺🇲 美国节点`load-balance`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://cp.cloudflare.com/204`300,,20
custom_proxy_group=🌐 其他节点`load-balance`(^(?!.*(香港|新加坡|德国|日本|未知|美国|US|United States)).*)`http://cp.cloudflare.com/204`300,,20

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
